# Generated by Django 6.0.5 on 2026-05-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='stock.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
